name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches: [main]

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        env:
          BACKEND_SERVER_URL: ${{ secrets.BACKEND_SERVER_URL }}
        run: |
          echo "NEXT_PUBLIC_API_SERVER_URL=${{ secrets.SERVER_URL }}" >> .env.production
          echo "NEXT_PUBLIC_WS_SERVER_URL=${{ secrets.WS_SERVER_URL }}" >> .env.production
          echo "NEXT_PUBLIC_KAKAO_APP_KEY=${{ secrets.KAKAO_APP_KEY }}" >> .env.production
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
